# Generated by Django 5.2.8 on 2025-11-17 12:18

import dpp.models
import datetime
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('uncertainty', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CircularityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=datetime.date.today, help_text='When the assessment was made or updated.')),
            ],
        ),
        migrations.CreateModel(
            name='CircularityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('is_static', models.BooleanField(choices=[(True, 'Static'), (False, 'Dynamic')], default=True)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Material name')),
                ('density', models.FloatField(blank=True)),
                ('recycled_content', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Recycled content (%)')),
                ('recyclable_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Recyclable material (%)')),
                ('biobased_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Bio-based material (%)')),
                ('reused_fraction', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Reused material (%)')),
                ('renewable_fraction', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Sustainable and renewable material (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('type', models.CharField(choices=[('Technical document', [('technical_drawing', 'Technical drawing'), ('safety_sheet', 'Safety sheet'), ('conformity_certificate', 'Conformity certificate'), ('other', 'Other')]), ('Compliance document', [('compliance', 'Compliance report'), ('quality_cert', 'Quality certificate'), ('safety_data', 'Safety data sheet'), ('legal', 'Legal document'), ('labor', 'Labor compliance'), ('qms', 'Quality Management System certificate'), ('warranty', 'Warranty information'), ('spare_parts', 'Spare parts availability'), ('takeback', 'Return and take-back')]), ('Manuals', [('manual', 'User manual'), ('maintenance', 'Maintenance manual'), ('installation', 'Installation guide'), ('eol', 'End-of-life guidelines'), ('datasheet', 'Product data sheet')]), ('Labels', [('label', 'Voluntary label'), ('energy_label', 'Energy label'), ('ecolabel', 'Ecolabel'), ('recycling_label', 'Recycling label'), ('legal', 'Legal markings')])], max_length=25, verbose_name='Document type')),
                ('language', models.CharField(blank=True, max_length=40)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(max_length=40)),
                ('is_environmental', models.BooleanField(choices=[(True, 'Environmental'), (False, 'Socioeconomic')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('label', models.CharField(choices=[('installation', 'Installation / assembly'), ('use', 'Use'), ('repair', 'Repair'), ('maintenance', 'Maintenance'), ('refurbishment', 'Refurbishment'), ('disassembly', 'Disassembly'), ('disposal', 'Disposal')], max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('registration_number', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('version', models.CharField(max_length=20)),
                ('access_link', models.URLField(blank=True)),
                ('access_policy', models.URLField(blank=True)),
                ('access_log_enabled', models.BooleanField(default=True)),
                ('verification_type', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Digital signature'), (2, 'Third party'), (3, 'Blockchain')], default=0)),
                ('credential_format', models.CharField(choices=[('json_ld', 'JSON-LD'), ('verifialble', 'Verifiable credential'), ('xml', 'XML'), ('other', 'Other')], max_length=50)),
                ('storage_location', models.SmallIntegerField(choices=[(0, 'Undeclared'), (1, 'On-premise server'), (2, 'Commercial cloud server'), (3, 'Centralized certified server'), (4, 'Decentralized storage')])),
                ('audit_trail_mechanism', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Log files'), (2, 'immutable ledger')])),
                ('update_interval', models.CharField(choices=[('-', 'never'), ('W', 'weekly'), ('M', 'monthly'), ('Q', 'quarterly'), ('A', 'annually'), ('E', 'event_driven')], default='-', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model or product name')),
                ('unit', models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'cubic meters'), ('ft3', 'cubic feet')])], default='pcs', max_length=3)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('weight', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='kg', max_length=2)),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_unit', models.CharField(choices=[('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'cubic meters'), ('ft3', 'cubic feet')], default='m3', max_length=3)),
                ('taric_code', models.CharField(blank=True, help_text='TARIC (customs code)', max_length=20)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System classification (customs code)', max_length=10)),
                ('warranty_duration', models.DurationField(default=datetime.timedelta(0), help_text='Warranty duration as a time delta')),
                ('spare_parts_availability_duration', models.DurationField(default=datetime.timedelta(0), help_text='Spare parts availability duration as a time delta')),
                ('takeback_system', models.CharField(choices=[('no', 'No take-back system'), ('basic', 'Collection on request'), ('active', 'Structured take-back with dedicated channels or collection points'), ('advanced', 'Certified, traceable take-back system')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_outsourced', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircularityEnabler',
            fields=[
                ('circularityscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.circularityscore')),
                ('type', models.CharField(choices=[('design', 'Design for circularity'), ('business_model', 'Circular business model'), ('process', 'Circular process or technology'), ('other', 'Other enabler')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description and functionality', max_length=300)),
            ],
            bases=('dpp.circularityscore',),
        ),
        migrations.CreateModel(
            name='CircularityTracker',
            fields=[
                ('circularityscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.circularityscore')),
                ('name', models.CharField(help_text='The type of traceability system or device in the product', max_length=50)),
                ('description', models.TextField(blank=True, help_text='A short description of the device or system', max_length=200)),
                ('functionality', models.TextField(blank=True, help_text='A short description of the intended functionality', max_length=200)),
            ],
            bases=('dpp.circularityscore',),
        ),
        migrations.AddField(
            model_name='circularityscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.circularityevaluation'),
        ),
        migrations.AddField(
            model_name='circularityscore',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.circularityindicator'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.organization')),
                ('vat_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            bases=('dpp.organization',),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.organization')),
                ('type', models.CharField(choices=[('university', 'University'), ('research', 'Research institute'), ('governmental', 'Government agency'), ('ngo', 'Non-governmental organization'), ('statistical', 'Statistical office'), ('accountant', 'Accountant office'), ('legal', 'Legal institution'), ('other', 'Other')], max_length=30)),
            ],
            bases=('dpp.organization',),
        ),
        migrations.CreateModel(
            name='CriticalRawMaterial',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.material')),
                ('origin_country', django_countries.fields.CountryField(max_length=2)),
                ('supply_risk_level', models.CharField(max_length=10)),
                ('substance_concentration', models.FloatField()),
                ('concentration_unit', models.CharField(max_length=20)),
            ],
            bases=('dpp.material',),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_legal_documents', to='dpp.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='instructions',
            field=models.ManyToManyField(blank=True, help_text='Instructions included in this document (ony for manauals)', to='dpp.instruction'),
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('producttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.producttype')),
            ],
            bases=('dpp.producttype',),
        ),
        migrations.CreateModel(
            name='SecondaryProduct',
            fields=[
                ('producttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.producttype')),
                ('circularity', models.CharField(choices=[('R3', 'reused'), ('R5', 'refurbished'), ('R6', 'remanufactured'), ('R7', 'repurposed'), ('R8', 'recycled'), ('in', 'incinerated'), ('lf', 'landfilled'), ('-', 'unknown')], default='-', max_length=2)),
                ('is_waste', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
            bases=('dpp.producttype',),
        ),
        migrations.AddField(
            model_name='producttype',
            name='quality_compliance_documents',
            field=models.ManyToManyField(blank=True, to='dpp.document'),
        ),
        migrations.CreateModel(
            name='OldCircularityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_static', models.BooleanField(choices=[(True, 'Static'), (False, 'Dynamic')], default=True)),
                ('name', models.CharField(choices=[('R0 - Refuse', [('hazardous', 'Hazardous substances'), ('fossil', 'Fossil energy use'), ('nonrenewable', 'Non-renewable materials'), ('other', 'Other materials'), ('consumption', 'Avoided product consumption')]), ('R1 - Rethink', [('modularity', 'Modularity'), ('product_takeback', 'Product take-back'), ('crm', 'Critical Materials'), ('shared_use', 'Shared use'), ('durability', 'Durability'), ('potential_use_during_lifetime', 'Potential use during lifetime'), ('multifunctionality', 'Multifunctionality'), ('modularity_score', 'Modularity score'), ('materials', 'Materials'), ('number_of_components', 'Number of components'), ('material_composition_complexity', 'Material composition complexity'), ('tools_required', 'Number of tools required'), ('separable_pieces_ratio', 'Separable pieces ratio')]), ('R2 - Reduce', [('reduce_raw_materials_intensity', 'Raw materials intensity reduction'), ('reduce_energy_intensity', 'Energy intensity reduction'), ('reduce_energy_consumption', 'Energy consumption reduction'), ('reduce_waste_generation', 'Waste generation reduction'), ('reduce_material_losses', 'Material losses reduction'), ('reduce_water_intensity', 'Water intensity reduction'), ('reduce_water_consumption', 'Water consumption')]), ('R3 - Reuse', [('reuse_rate', 'Reuse rate'), ('product_takeback', 'Product take-back'), ('consumer_awareness', 'Consumer awareness'), ('potential_use', 'Potential use'), ('ownership_time', 'Ownership time'), ('voidance_of_reuse_barriers', 'Voidance of reuse rarriers'), ('reuse_potential', 'Reuse potential'), ('costs_of_reuse', 'Costs of reuse'), ('access_to_parts', 'Access to high-value parts')]), ('R4 - Repair', [('longevity_extension', 'Longevity extension'), ('extension_of_producer_responsibility', 'Extension of producer responsibility'), ('consumer_awareness', 'Consumer awareness'), ('potential_repair', 'Potential repair'), ('repairability_score', 'Repairability score'), ('durability_score', 'Durability score'), ('non_destructive_disassembly_score', 'Non-destructive disassembly score'), ('ease_of_reassembly', 'Ease of reassembly')]), ('R5 - Refurbish', [('product_takeback', 'Product take-back'), ('refurbished_content', 'Refurbished content'), ('refurbishment_potential', 'Refurbishment rotential'), ('refurbishment_score', 'Refurbishment score'), ('upgradability_score', 'Upgradability score')]), ('R6 - Remanufacture', [('product_takeback', 'Product take-back'), ('remanufacturing_effectiveness', 'Remanufacturing effectiveness'), ('consumer_awareness', 'Consumer awareness'), ('remanufacturing_content', 'Remanufacturing content'), ('remanufacturing_score', 'Remanufacturing score')]), ('R7 - Repurpose', [('secondary_raw_materials', 'Secondary raw materials'), ('hazardous_waste_diverted', 'Hazardous waste diverted from disposal'), ('nonhazardous_waste_diverted', 'Non-hazardous waste diverted from disposal')]), ('R8 - Recycle', [('overall_recycling_rates', 'Overall recycling rates'), ('recycling_rate_for_waste_streams', 'Recycling rate for waste streams'), ('waste_generation', 'Waste generation'), ('reverse_logistics', 'Reverse logistics'), ('recycling_potential', 'Recycling potential'), ('design_for_recyclability', 'Design for recyclability'), ('recycling_compatibility_score', 'Recycling compatibility score'), ('material_homogeneity_score', 'Material homogeneity score'), ('hazardous_substance_barrier', 'Hazardous substance barrier'), ('high_purity_sorting_possible', 'High purity sorting possible'), ('use_of_recyclable_materials', 'Use of easily recyclable materials'), ('recycling_collection_rate', 'Recycling collection rate')]), ('R9 - Recover', [('waste_diversion_from_landfill', 'Waste diversion from landfill'), ('potential_recovery', 'Potential recovery'), ('hazardous_waste_disposal', 'Hazardous waste directed to disposal'), ('nonhazardous_waste_disposal', 'Non-hazardous waste directed to disposal'), ('energy_recoverability_benefit', 'Energy recoverability benefit'), ('raw_materials_input', 'Raw materials input')])], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='circularityevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.producttype'),
        ),
        migrations.CreateModel(
            name='SharedProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.process')),
            ],
            bases=('dpp.process',),
        ),
        migrations.AddField(
            model_name='process',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpp.producttype'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('batch_number', models.IntegerField(blank=True)),
                ('CPV_code', models.CharField(blank=True, help_text='Common Procurement Vocabulary code', max_length=20)),
                ('GS1_GPC_code', models.CharField(blank=True, help_text='Global Product Classification code', max_length=20)),
                ('GTIN_code', models.CharField(help_text='Global Trade Item Number (or comparable)', max_length=20)),
                ('production_date', models.DateField(default=datetime.date.today)),
                ('DPP_metadata', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dpp.metadata')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dpp.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('modified_at', models.DateField(auto_now=True)),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dpp.producttype')),
                ('operator', models.ForeignKey(blank=True, on_delete=models.SET(dpp.models.get_unknown_company), to='dpp.company')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.productionline'),
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, choices=[('preventive_maintenance', 'Preventive maintenance'), ('corrective_maintenance', 'Corrective maintenance'), ('modification', 'Modification'), ('upgrade', 'Upgrade'), ('eol', 'End-of-life treatment')], max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpp.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_events', to='dpp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('modification_category', models.CharField(choices=[('corrective', 'Repair'), ('software', 'Software update'), ('performance', 'Performance upgrade'), ('safety', 'Safety improvement'), ('energy_optimization', 'Energy optimization'), ('compliance', 'Compliance update'), ('other', 'Other')], max_length=50)),
                ('affected_functionality', models.CharField(blank=True, max_length=500)),
                ('software_or_hardware', models.BooleanField(choices=[(True, 'Software'), (False, 'Hardware')])),
                ('root_cause', models.TextField(blank=True, max_length=300)),
                ('diagnostics_performed', models.TextField(blank=True, max_length=300)),
                ('corrective_action', models.TextField(blank=True, max_length=300)),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.serviceevent')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacedComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed', to='dpp.product')),
                ('old_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced', to='dpp.product')),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_components', to='dpp.servicerecord')),
            ],
        ),
        migrations.CreateModel(
            name='EndOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('recycling', 'Recycling'), ('disposal', 'Disposal'), ('incineration', 'Incineration'), ('stockpiling', 'Stockpiling')], max_length=20)),
                ('affected_component', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dpp.product')),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_life', to='dpp.servicerecord')),
            ],
        ),
        migrations.CreateModel(
            name='SustainablityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_amount', models.FloatField()),
                ('system_boundaries', models.CharField(blank=True, max_length=200)),
                ('geographical_scope', models.CharField(blank=True, choices=[('EU', 'European Union (EU)'), ('c', 'Country-specific'), ('glo', 'Global'), ('-', 'Other')], max_length=4)),
                ('temporal_scope', models.CharField(default='<function SustainablityEvaluation.get_year at 0x7681c043fce0>', max_length=50)),
                ('impact_assessment_method', models.CharField(blank=True, help_text='Specify the environmental impact assessment method. E.g. EF 3.0, ReCiPe, ILCD, TRACI.', max_length=50)),
                ('software_used', models.CharField(blank=True, help_text='Indicate the assessment software used. E.g. OpenLCA, GaBi, SimaPro, Umberto.', max_length=50)),
                ('allocation_method', models.CharField(blank=True, choices=[('mass', 'Mass-based'), ('econom', 'Economic (price-based)'), ('energy', 'Energy-based'), ('other', 'Other')], help_text='How are impacts allocated for co-production processes?', max_length=6)),
                ('assessment_date', models.DateField(default=datetime.date.today)),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.productionline')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dpp.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_value', models.FloatField()),
                ('upstream_phase', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('manufacturing_phase', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('use_phase', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('end_of_life_phase', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('scope_1_2_3', models.FloatField(help_text='Total greenhouse gas emissions associated with the product over its lifecycle, expressed as kg CO<sub>2</sub> equivalents.', verbose_name='Scope 1+2+3 CO<sub>2</sub> emission')),
                ('impact_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.impactcategory')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.sustainablityevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.company')),
                ('EORI_number', models.CharField(blank=True, max_length=100)),
            ],
            bases=('dpp.company',),
        ),
        migrations.CreateModel(
            name='ServiceOperator',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.company')),
                ('service_description', models.CharField(max_length=100)),
            ],
            bases=('dpp.company',),
        ),
        migrations.AddField(
            model_name='producttype',
            name='origin',
            field=models.ForeignKey(on_delete=models.SET(dpp.models.get_unknown_company), to='dpp.company'),
        ),
        migrations.AddField(
            model_name='process',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpp.company'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dpp.institution'),
        ),
        migrations.AddField(
            model_name='circularityevaluation',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dpp.institution'),
        ),
        migrations.CreateModel(
            name='HazardousMaterial',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.material')),
                ('CAS_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('substance_concentration', models.FloatField(blank=True)),
                ('concentration_unit', models.CharField(blank=True, max_length=20)),
                ('safety_instructions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_safety_instructions', to='dpp.document')),
                ('substance_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_location', to='dpp.document')),
            ],
            bases=('dpp.material',),
        ),
        migrations.CreateModel(
            name='PackagingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_ratio', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_info', to='dpp.producttype')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_packaging', to='dpp.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='dpp.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='dpp.producttype')),
            ],
            options={
                'ordering': ['product', 'material'],
                'unique_together': {('product', 'material')},
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'cubic meters'), ('ft3', 'cubic feet')])], max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='dpp.producttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='dpp.producttype')),
            ],
            options={
                'ordering': ['product', 'component'],
                'unique_together': {('product', 'component')},
            },
        ),
        migrations.CreateModel(
            name='EnvExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('exchange_type', models.CharField(choices=[('in', 'Input'), ('out', 'Output'), ('ff', 'functional flow')], max_length=3)),
                ('is_proxy', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='The actual product is different')),
                ('observed', models.BooleanField(choices=[(True, 'Measured'), (False, 'Modeled or calculated')], default=False, verbose_name='Quantity is')),
                ('uncertainty_type', models.CharField(choices=[('none', 'No uncertainty'), ('na', 'Not available'), ('interval', 'Interval (min-max)'), ('normal', 'Normal distribution'), ('lognormal istribution', 'Lognormal distribution'), ('triangular', 'Triangular distribution')], default='none', max_length=30)),
                ('loc', models.FloatField(blank=True)),
                ('scale', models.FloatField(blank=True)),
                ('shape', models.FloatField(blank=True)),
                ('minimum', models.FloatField(blank=True)),
                ('maximum', models.FloatField(blank=True)),
                ('compartment', models.CharField(choices=[('air', 'air'), ('soil', 'soil'), ('groundwater', 'groundwater'), ('seawater', 'seawater'), ('surface_water', 'surface water')], max_length=20)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.emission')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_exchanges', to='dpp.process')),
            ],
            options={
                'ordering': ['process', 'substance'],
                'unique_together': {('substance', 'compartment', 'exchange_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('exchange_type', models.CharField(choices=[('in', 'Input'), ('out', 'Output'), ('ff', 'functional flow')], max_length=3)),
                ('is_proxy', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='The actual product is different')),
                ('observed', models.BooleanField(choices=[(True, 'Measured'), (False, 'Modeled or calculated')], default=False, verbose_name='Quantity is')),
                ('uncertainty_type', models.CharField(choices=[('none', 'No uncertainty'), ('na', 'Not available'), ('interval', 'Interval (min-max)'), ('normal', 'Normal distribution'), ('lognormal istribution', 'Lognormal distribution'), ('triangular', 'Triangular distribution')], default='none', max_length=30)),
                ('loc', models.FloatField(blank=True)),
                ('scale', models.FloatField(blank=True)),
                ('shape', models.FloatField(blank=True)),
                ('minimum', models.FloatField(blank=True)),
                ('maximum', models.FloatField(blank=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_exchanges', to='dpp.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_process', to='dpp.producttype')),
            ],
            options={
                'ordering': ['process', 'product'],
                'unique_together': {('product', 'process', 'exchange_type')},
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='vendor_or_importer',
            field=models.ForeignKey(on_delete=models.SET(dpp.models.get_unknown_importer), related_name='sold_products', to='dpp.importer'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.serviceoperator'),
        ),
    ]
