# Generated by Django 5.2.8 on 2025-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainablityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainablityEvaluation.get_year at 0x71b0b1e3aac0>', max_length=50),
        ),
    ]
