# Generated by Django 5.2.8 on 2025-11-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0002_alter_sustainablityevaluation_temporal_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='circularityevaluation',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report describing the circularity assessment, and manual for monitoring and updating the circularity metrics.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circularity_reports', to='dpp.document'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='energy_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_balance', to='dpp.document'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='mass_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_balance', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Technical document', [('technical_drawing', 'Technical drawing'), ('safety_sheet', 'Safety sheet'), ('conformity_certificate', 'Conformity certificate'), ('mass_balance', 'Mass balance'), ('energy_balance', 'Energy balance'), ('other', 'Other')]), ('Compliance document', [('compliance', 'Compliance report'), ('quality_cert', 'Quality certificate'), ('safety_data', 'Safety data sheet'), ('legal', 'Legal document'), ('labor', 'Labor compliance'), ('qms', 'Quality Management System certificate'), ('warranty', 'Warranty information'), ('spare_parts', 'Spare parts availability'), ('takeback', 'Return and take-back')]), ('Manuals', [('manual', 'User manual'), ('maintenance', 'Maintenance manual'), ('installation', 'Installation guide'), ('eol', 'End-of-life guidelines'), ('datasheet', 'Product data sheet')]), ('Labels', [('label', 'Voluntary label'), ('energy_label', 'Energy label'), ('ecolabel', 'Ecolabel'), ('recycling_label', 'Recycling label'), ('legal', 'Legal markings')])], max_length=25, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='sustainablityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainablityEvaluation.get_year at 0x7efc2a946d40>', max_length=50),
        ),
    ]
