# Generated by Django 5.2.8 on 2025-11-17 19:06

import dpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0003_circularityevaluation_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='origin',
            field=models.ForeignKey(on_delete=models.SET(dpp.models.get_unknown_company), related_name='manufactured_products', to='dpp.company'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='vendor_or_importer',
            field=models.ForeignKey(blank=True, on_delete=models.SET(dpp.models.get_unknown_importer), related_name='sold_products', to='dpp.importer'),
        ),
        migrations.AlterField(
            model_name='sustainablityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainablityEvaluation.get_year at 0x78e0e6a8afc0>', max_length=50),
        ),
    ]
