# Generated by Django 5.2.8 on 2025-11-24 13:34

from django.db import migrations, models
import django.db.models.deletion


def populate_activity_ptr(apps, schema_editor):
    Process = apps.get_model('dpp', 'Process')
    Activity = apps.get_model('dpp', 'Activity')
    
    for process in Process.objects.all():
        # Create the parent Activity row
        activity = Activity.objects.create(id=process.pk, name=process.name)
        # Link the new Activity to process
        process.activity_ptr = activity
        process.save(update_fields=['activity_ptr_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0004_alter_producttype_origin_and_more'),
    ]

    operations = [
        # 0. Move SharedProcess from table to proxy model
        migrations.DeleteModel(name='SharedProcess'),
        migrations.CreateModel(
            name='SharedProcess',
            fields=[],
            options={'proxy': True},
            bases=('dpp.Process',),
        ),

        migrations.DeleteModel(name='ProductExchange'),
        migrations.DeleteModel(name='EnvExchange'),

        # 3a. Create the new Activity table
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        # 3b. Add the activity_ptr field with a temporary default/null=True
        migrations.AddField(
            model_name='process',
            name='activity_ptr',
            field=models.OneToOneField(
                null=True,  # temporary
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to='dpp.Activity',
            ),
        ),
        # 3c. Populate the pointers + copy common data
        migrations.RunPython(populate_activity_ptr, reverse_code=migrations.RunPython.noop),
        
        # 3c. Now make it non-nullable
        migrations.AlterField(
            model_name='process',
            name='activity_ptr',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                to='dpp.Activity',
            ),
        ),
    ]