# Generated by Django 5.2.8 on 2025-11-25 09:10

import datetime
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import dpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0005_add_activity_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcess',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.activity')),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Average market process',
                'verbose_name_plural': 'Average market processes',
            },
            bases=('dpp.activity',),
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='quality_compliance_documents',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='spare_parts_availability_duration',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='vendor_or_importer',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='warranty_duration',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='takeback_system',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['product', 'component'], 'verbose_name_plural': 'Bills of Materials'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='impactcategory',
            options={'verbose_name_plural': 'Impact Categories'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name_plural': 'Metadata'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='sharedprocess',
            options={'verbose_name': 'Auxiliary process', 'verbose_name_plural': 'Auxiliary processes'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='process',
            name='id',
        ),
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='name',
        ),
        migrations.AddField(
            model_name='productionline',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm<sup>3</sup>'), ('dm3', 'dm<sup>3</sup>'), ('m3', 'm<sup>3</sup> (cubic meters)'), ('ft3', 'ft<sup>3</sup> (cubic feet)')]), ('Energy', [('kWh', 'kWh'), ('MWh', 'MWh'), ('MJ', 'MJ'), ('GJ', 'GJ')])], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='instructions',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply. Instructions included in this document (ony for manauals)', to='dpp.instruction'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='is_environmental',
            field=models.BooleanField(choices=[(True, 'Environmental'), (False, 'Socioeconomic')], default=True, verbose_name='Type of impact'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='access_link',
            field=models.URLField(blank=True, help_text='URL to full DPP record.'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='access_policy',
            field=models.URLField(blank=True, help_text='URL to data access terms and conditions.'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='audit_trail_mechanism',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Log files'), (2, 'Immutable ledger')], default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dpp.company', verbose_name='Responsible Economic Operator'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='storage_location',
            field=models.SmallIntegerField(choices=[(0, 'Undeclared'), (1, 'On-premise server'), (2, 'Commercial cloud server'), (3, 'Centralized certified server'), (4, 'Decentralized storage')], default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.activity'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Outsourced'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='final_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='dpp.producttype'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(dpp.models.get_unknown_company), to='dpp.company'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm<sup>3</sup>'), ('dm3', 'dm<sup>3</sup>'), ('m3', 'm<sup>3</sup> (cubic meters)'), ('ft3', 'ft<sup>3</sup> (cubic feet)')]), ('Energy', [('kWh', 'kWh'), ('MWh', 'MWh'), ('MJ', 'MJ'), ('GJ', 'GJ')])], default='pcs', max_length=3),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='volume_unit',
            field=models.CharField(choices=[('l', 'liters'), ('cm3', 'cm<sup>3</sup>'), ('dm3', 'dm<sup>3</sup>'), ('m3', 'm<sup>3</sup> (cubic meters)'), ('ft3', 'ft<sup>3</sup> (cubic feet)')], default='m3', max_length=3),
        ),
        migrations.AlterField(
            model_name='secondaryproduct',
            name='is_waste',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=100, verbose_name='Display name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='dpp.producttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.company')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='SustainabilityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_amount', models.FloatField()),
                ('system_boundaries', models.CharField(blank=True, max_length=200)),
                ('geographical_scope', models.CharField(blank=True, choices=[('EU', 'European Union (EU)'), ('c', 'Country-specific'), ('glo', 'Global'), ('-', 'Other')], max_length=4)),
                ('temporal_scope', models.CharField(default='<function SustainabilityEvaluation.get_year at 0x77132e3f58a0>', max_length=50)),
                ('impact_assessment_method', models.CharField(blank=True, help_text='Specify the environmental impact assessment method. E.g. EF 3.0, ReCiPe, ILCD, TRACI.', max_length=50)),
                ('software_used', models.CharField(blank=True, help_text='Indicate the assessment software used. E.g. OpenLCA, GaBi, SimaPro, Umberto.', max_length=50)),
                ('allocation_method', models.CharField(blank=True, choices=[('mass', 'Mass-based'), ('econom', 'Economic (price-based)'), ('energy', 'Energy-based'), ('other', 'Other')], help_text='How are impacts allocated for co-production processes?', max_length=6)),
                ('assessment_date', models.DateField(default=datetime.date.today)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dpp.institution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.producttype')),
            ],
        ),
        migrations.AlterField(
            model_name='sustainabilityscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.sustainabilityevaluation'),
        ),
        migrations.CreateModel(
            name='DppProduct',
            fields=[
                ('producttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.producttype')),
                ('warranty_period_months', models.PositiveSmallIntegerField(default=0, help_text='Warranty period in months')),
                ('warranty_duration', models.DecimalField(decimal_places=1, default=0, help_text='Warranty period in years', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('spare_parts_availability_duration', models.DecimalField(decimal_places=1, default=0, help_text='Spare parts availability in years', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('takeback_system', models.CharField(choices=[('no', 'No take-back system'), ('basic', 'Collection on request'), ('active', 'Structured take-back with dedicated channels or collection points'), ('advanced', 'Certified, traceable take-back system')], default='no', max_length=10)),
                ('origin', models.ForeignKey(on_delete=models.SET(dpp.models.get_unknown_company), related_name='manufactured_products', to='dpp.company')),
                ('quality_compliance_documents', models.ManyToManyField(blank=True, to='dpp.document')),
                ('vendor_or_importer', models.ForeignKey(blank=True, null=True, on_delete=models.SET(dpp.models.get_unknown_importer), related_name='sold_products', to='dpp.importer')),
            ],
            bases=('dpp.producttype',),
        ),
        migrations.CreateModel(
            name='EnvExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('exchange_type', models.CharField(choices=[('in', 'Input'), ('out', 'Output'), ('ff', 'functional flow')], max_length=3)),
                ('is_proxy', models.BooleanField(default=False, verbose_name='This is an approximation of the actual product')),
                ('observed', models.BooleanField(choices=[(True, 'Measured'), (False, 'Modeled or calculated')], default=False, verbose_name='Quantity is')),
                ('uncertainty_type', models.CharField(choices=[('none', 'No uncertainty'), ('na', 'Not available'), ('interval', 'Interval (min-max)'), ('normal', 'Normal distribution'), ('lognormal istribution', 'Lognormal distribution'), ('triangular', 'Triangular distribution')], default='none', max_length=30)),
                ('loc', models.FloatField(blank=True)),
                ('scale', models.FloatField(blank=True)),
                ('shape', models.FloatField(blank=True)),
                ('minimum', models.FloatField(blank=True)),
                ('maximum', models.FloatField(blank=True)),
                ('compartment', models.CharField(choices=[('air', 'air'), ('soil', 'soil'), ('groundwater', 'groundwater'), ('seawater', 'seawater'), ('surface_water', 'surface water')], max_length=20)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_exchanges', to='dpp.process')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.emission')),
            ],
            options={
                'ordering': ['process', 'substance'],
                'unique_together': {('substance', 'compartment', 'exchange_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('exchange_type', models.CharField(choices=[('in', 'Input'), ('out', 'Output'), ('ff', 'functional flow')], max_length=3)),
                ('is_proxy', models.BooleanField(default=False, verbose_name='This is an approximation of the actual product')),
                ('observed', models.BooleanField(choices=[(True, 'Measured'), (False, 'Modeled or calculated')], default=False, verbose_name='Quantity is')),
                ('uncertainty_type', models.CharField(choices=[('none', 'No uncertainty'), ('na', 'Not available'), ('interval', 'Interval (min-max)'), ('normal', 'Normal distribution'), ('lognormal istribution', 'Lognormal distribution'), ('triangular', 'Triangular distribution')], default='none', max_length=30)),
                ('loc', models.FloatField(blank=True)),
                ('scale', models.FloatField(blank=True)),
                ('shape', models.FloatField(blank=True)),
                ('minimum', models.FloatField(blank=True)),
                ('maximum', models.FloatField(blank=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_exchanges', to='dpp.activity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_process', to='dpp.producttype')),
            ],
            options={
                'ordering': ['process', 'product'],
                'unique_together': {('product', 'process', 'exchange_type')},
            },
        ),
        migrations.DeleteModel(
            name='SustainablityEvaluation',
        ),
    ]
