# Generated by Django 5.2.8 on 2025-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0006_backgroundprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundprocess',
            name='database',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x751b1f7f5120>', max_length=50),
        ),
    ]
