# Generated by Django 5.2.8 on 2025-11-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0007_backgroundprocess_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='dpp.producttype'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7f660a5ed080>', max_length=50),
        ),
    ]
