# Generated by Django 5.2.8 on 2025-11-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0008_alter_process_functional_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundprocess',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by_other', to='dpp.producttype', verbose_name='Main product'),
        ),
        migrations.AlterField(
            model_name='process',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='dpp.producttype', verbose_name='Main product'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='final_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='dpp.producttype', verbose_name='Final Product'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7c77d83e9080>', max_length=50),
        ),
    ]
