# Generated by Django 5.2.8 on 2025-11-27 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0009_backgroundprocess_functional_flow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envexchange',
            options={'ordering': ['process', 'substance'], 'verbose_name': 'Emissions & Extractions'},
        ),
        migrations.AlterModelOptions(
            name='impactcategory',
            options={'verbose_name_plural': 'Impact categories'},
        ),
        migrations.RenameField(
            model_name='dppproduct',
            old_name='warranty_duration',
            new_name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='dppproduct',
            name='warranty_period_months',
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='loc',
            field=models.FloatField(blank=True, null=True, verbose_name='Mean or median'),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='maximum',
            field=models.FloatField(blank=True, help_text='for interval and triangular distribution', null=True),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='minimum',
            field=models.FloatField(blank=True, help_text='for interval and triangular distribution', null=True),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Standard deviation'),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='shape',
            field=models.FloatField(blank=True, help_text='for lognormal distribution', null=True),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='dpp.emission'),
        ),
        migrations.AlterField(
            model_name='hazardousmaterial',
            name='concentration_unit',
            field=models.CharField(choices=[('wt', 'Weight fraction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hazardousmaterial',
            name='substance_concentration',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='batch_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='loc',
            field=models.FloatField(blank=True, null=True, verbose_name='Mean or median'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='maximum',
            field=models.FloatField(blank=True, help_text='for interval and triangular distribution', null=True),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='minimum',
            field=models.FloatField(blank=True, help_text='for interval and triangular distribution', null=True),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_by', to='dpp.producttype'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Standard deviation'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='shape',
            field=models.FloatField(blank=True, help_text='for lognormal distribution', null=True),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7785903216c0>', max_length=50),
        ),
    ]
