# Generated by Django 5.2.8 on 2025-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0010_alter_envexchange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circularityindicator',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x70f1b527d620>', max_length=50),
        ),
        migrations.DeleteModel(
            name='OldCircularityIndicator',
        ),
    ]
