# Generated by Django 5.2.8 on 2025-12-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0011_alter_circularityindicator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'm3 (cubic meters)'), ('ft3', 'ft3 (cubic feet)')]), ('Energy', [('kWh', 'kWh'), ('MWh', 'MWh'), ('MJ', 'MJ'), ('GJ', 'GJ')])], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'm3 (cubic meters)'), ('ft3', 'ft3 (cubic feet)')]), ('Energy', [('kWh', 'kWh'), ('MWh', 'MWh'), ('MJ', 'MJ'), ('GJ', 'GJ')])], default='pcs', max_length=3),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='volume_unit',
            field=models.CharField(choices=[('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'm3 (cubic meters)'), ('ft3', 'ft3 (cubic feet)')], default='m3', max_length=3),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7c9f8026d620>', max_length=50),
        ),
    ]
