# Generated by Django 5.2.8 on 2025-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0012_alter_billofmaterials_unit_alter_company_vat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='amount',
            field=models.FloatField(default=1, help_text='Number of units produced'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='unit',
            field=models.CharField(default='pcs', help_text='How the product is counted, e.g. pcs, bottles, sheets, bags', max_length=15),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7d7c929cf4c0>', max_length=50),
        ),
    ]
