# Generated by Django 5.2.8 on 2025-12-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0013_process_amount_alter_producttype_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='unit',
            field=models.CharField(default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x77b4f6d56de0>', max_length=50),
        ),
    ]
