# Generated by Django 5.2.8 on 2025-12-10 12:36

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import dpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0014_emission_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(verbose_name='Release date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Phase-out date')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductItem',
        ),
        migrations.RenameModel(
            old_name='ReplacedComponents',
            new_name='ReplacedComponent',
        ),
        migrations.AlterModelOptions(
            name='envexchange',
            options={'ordering': ['process', 'substance'], 'verbose_name': 'Emission or Extraction', 'verbose_name_plural': 'Emissions & Extractions'},
        ),
        migrations.RenameField(
            model_name='envexchange',
            old_name='exchange_type',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='productexchange',
            old_name='exchange_type',
            new_name='direction',
        ),
        migrations.AlterUniqueTogether(
            name='envexchange',
            unique_together={('substance', 'compartment', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='productexchange',
            unique_together={('product', 'process', 'direction')},
        ),
        migrations.RemoveField(
            model_name='composition',
            name='fraction',
        ),
        migrations.RemoveField(
            model_name='criticalrawmaterial',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='is_environmental',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='unit',
        ),
        migrations.AddField(
            model_name='composition',
            name='origin_country',
            field=django_countries.fields.CountryField(blank=True, help_text='Only fill for Critical Raw Materials', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='quantity',
            field=models.FloatField(default=0, help_text='The amount of material present in product.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composition',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='dpp.material'),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='uncertainty_type',
            field=models.CharField(choices=[('none', 'No uncertainty'), ('na', 'Not available'), ('interval', 'Interval (min-max)'), ('normal', 'Normal distribution'), ('lognormal istribution', 'Lognormal distribution'), ('triangular', 'Triangular distribution')], default='none', help_text='If the amount is uncertain, how can this uncertainty be described?', max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_documents',
            field=models.ForeignKey(blank=True, help_text='Add official legal documentation associated with the company. This may include licenses, registration papers, permits, or other legally mandated certificates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_legal_documents', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='process',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='dpp.producttype', verbose_name='Main output'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='uncertainty_type',
            field=models.CharField(choices=[('none', 'No uncertainty'), ('na', 'Not available'), ('interval', 'Interval (min-max)'), ('normal', 'Normal distribution'), ('lognormal istribution', 'Lognormal distribution'), ('triangular', 'Triangular distribution')], default='none', help_text='If the amount is uncertain, how can this uncertainty be described?', max_length=30),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='energy_balance',
            field=models.ForeignKey(blank=True, help_text='Add a document showing all energy flows going in and out of the production line. (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_balance', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='final_product',
            field=models.OneToOneField(help_text='The output product of this production line', on_delete=django.db.models.deletion.RESTRICT, to='dpp.producttype', verbose_name='Final product'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='mass_balance',
            field=models.ForeignKey(blank=True, help_text='Add a document showing all material flows going in and out of the production line. (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_balance', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(dpp.models.get_unknown_company), to='dpp.company', verbose_name='Producing company'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System classification (customs code)', max_length=10, verbose_name='HS code'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='unit',
            field=models.CharField(default='pcs', help_text='How the product is counted, e.g. pcs, bottles, sheets, kWh', max_length=15),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='weight',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight of 1 unit'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7687c576c900>', max_length=50),
        ),
        migrations.CreateModel(
            name='ImpactIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(max_length=40)),
                ('is_environmental', models.BooleanField(choices=[(True, 'Environmental'), (False, 'Socioeconomic')], default=True, verbose_name='Type of impact')),
                ('impact_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dpp.impactcategory')),
                ('indicator_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpp.indicatorset')),
            ],
        ),
        migrations.AlterField(
            model_name='sustainabilityscore',
            name='impact_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.impactindicator'),
        ),
    ]
