# Generated by Django 5.2.8 on 2025-12-12 10:05

import django.core.validators
import django.db.models.deletion
import dpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0015_indicatorset_rename_product_productitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='dppproduct'),
        migrations.RemoveField(
            model_name='packaginginfo',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='packaginginfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='secondaryproduct',
            name='producttype_ptr',
        ),
        migrations.DeleteModel(name='Packaging'),
        migrations.DeleteModel(name='PackagingInfo'),
        migrations.DeleteModel(name='secondaryproduct'),
        migrations.RenameModel('ProductType', 'ProductModel'),
        migrations.RemoveField(
            model_name='productmodel',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='volume_unit',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='batch_number',
        ),
        migrations.CreateModel(
            name='SecondaryProduct',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.productmodel')),
                ('circularity', models.CharField(choices=[('R3', 'reused'), ('R5', 'refurbished'), ('R6', 'remanufactured'), ('R7', 'repurposed'), ('R8', 'recycled'), ('in', 'incinerated'), ('lf', 'landfilled'), ('-', 'unknown')], default='-', max_length=2)),
                ('is_waste', models.BooleanField(default=False)),
            ],
            bases=('dpp.productmodel',),
        ),
        migrations.AddField(
            model_name='productexchange',
            name='type',
            field=models.CharField(choices=[('prod', 'Component (added to the product)'), ('cons', 'Consumable'), ('ener', 'Electricity or heat'), ('util', 'Utility or equipment'), ('waste', 'Waste')], default='prod', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7331d6a38400>', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.productmodel')),
                ('batch_number', models.PositiveIntegerField()),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='batch', to='dpp.productmodel')),
            ],
            bases=('dpp.productmodel',),
        ),
        migrations.AlterField(
            model_name='alias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='dpp.productmodel'),
        ),
        migrations.AlterField(
            model_name='backgroundprocess',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by_other', to='dpp.productmodel', verbose_name='Main product'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_by', to='dpp.productmodel'),
        ),
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight of 1 unit')),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='kg', max_length=2)),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_unit', models.CharField(choices=[('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'm3 (cubic meters)'), ('ft3', 'ft3 (cubic feet)')], default='m3', max_length=3)),
                ('density', models.FloatField(help_text='Density of the product, excluding packaging and empty space.', validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dpp.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_period', models.DecimalField(decimal_places=1, default=0, help_text='Warranty period in years', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('spare_parts_availability_duration', models.DecimalField(decimal_places=1, default=0, help_text='Spare parts availability in years', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('takeback_system', models.CharField(choices=[('no', 'No take-back system'), ('basic', 'Collection on request'), ('active', 'Structured take-back with dedicated channels or collection points'), ('advanced', 'Certified, traceable take-back system')], default='no', max_length=10)),
                ('origin', models.ForeignKey(on_delete=models.SET(dpp.models.get_unknown_company), related_name='manufactured_products', to='dpp.company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dpp.productmodel')),
                ('quality_compliance_documents', models.ManyToManyField(blank=True, to='dpp.document')),
                ('vendor_or_importer', models.ForeignKey(blank=True, null=True, on_delete=models.SET(dpp.models.get_unknown_importer), related_name='sold_products', to='dpp.importer')),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='dpp.productbatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='dpp.productmodel'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='dpp.productmodel'),
        ),
        migrations.AlterField(
            model_name='circularityevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.productmodel'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='dpp.productmodel'),
        ),
        migrations.AlterField(
            model_name='process',
            name='functional_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='dpp.productmodel', verbose_name='Main output'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='final_product',
            field=models.OneToOneField(help_text='The output product of this production line', on_delete=django.db.models.deletion.RESTRICT, to='dpp.productmodel', verbose_name='Final product'),
        ),
    ]
