# Generated by Django 5.2.8 on 2025-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0016_restructure_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperties',
            name='includes_packaging',
            field=models.BooleanField(default=False, verbose_name='The above includes packaging'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('Mass', [('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')]), ('Volume', [('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'm3 (cubic meters)'), ('ft3', 'ft3 (cubic feet)'), ('gal', 'gallons')]), ('Energy', [('kWh', 'kWh'), ('MWh', 'MWh'), ('MJ', 'MJ'), ('GJ', 'GJ')])], max_length=20),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='type',
            field=models.CharField(choices=[('prod', 'Component (added to the product)'), ('cons', 'Consumable'), ('pack', 'Packaging'), ('ener', 'Electricity or heat'), ('util', 'Utility or equipment'), ('waste', 'Waste')], max_length=5),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='volume_unit',
            field=models.CharField(choices=[('l', 'liters'), ('cm3', 'cm3'), ('dm3', 'dm3'), ('m3', 'm3 (cubic meters)'), ('ft3', 'ft3 (cubic feet)'), ('gal', 'gallons')], default='m3', max_length=3),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7214e8c08cc0>', max_length=50),
        ),
    ]
