# Generated by Django 5.2.8 on 2025-12-16 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0017_add_property_n_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='functional_flow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='dpp.productmodel', verbose_name='Main output'),
        ),
        migrations.AlterField(
            model_name='process',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bop', to='dpp.productionline'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7211a4f18400>', max_length=50),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40000)], verbose_name='Transport distance (km)')),
                ('mode', models.CharField(choices=[('ocean', 'Ship (ocean)'), ('NA', 'Unspecified')], default='NA', max_length=10, verbose_name='Main mode of transport')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='dpp.productmodel')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='dpp.productionline')),
            ],
        ),
        migrations.DeleteModel(
            name='BillOfMaterials',
        ),
    ]
