# Generated by Django 5.2.8 on 2025-12-17 15:41

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0018_alter_process_functional_flow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name', 'origin_country']},
        ),
        migrations.RemoveField(
            model_name='composition',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='hazardousmaterial',
            name='concentration_unit',
        ),
        migrations.RemoveField(
            model_name='hazardousmaterial',
            name='substance_concentration',
        ),
        migrations.RemoveField(
            model_name='hazardousmaterial',
            name='substance_location',
        ),
        migrations.AddField(
            model_name='composition',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='g', max_length=2),
        ),
        migrations.AddField(
            model_name='material',
            name='criticality_level',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('c', 'critical'), ('h', 'high'), ('m', 'intermediate')], default='', help_text='Only for Critical Raw Materials (CRMs): criticality indicator based on supply risk and economic importance.', max_length=1),
        ),
        migrations.AddField(
            model_name='material',
            name='origin_country',
            field=django_countries.fields.CountryField(blank=True, help_text='Only for Critical Raw Materials (CRMs)', max_length=2, null=True, verbose_name='Country of origin'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x724772964ea0>', max_length=50),
        ),
        migrations.DeleteModel(
            name='CriticalRawMaterial',
        ),
    ]
