# Generated by Django 5.2.8 on 2026-01-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0019_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dppdetails',
            options={'verbose_name': 'DPP details', 'verbose_name_plural': 'DPP details'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'verbose_name_plural': 'Product batches'},
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='amount',
            field=models.FloatField(default=1, help_text='Number of units produced'),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='db_code',
            field=models.CharField(blank=True, help_text='Unique ID in the source database', max_length=50),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='language',
            field=models.CharField(default='EN', help_text='Language used in descriptions', max_length=20),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='type',
            field=models.CharField(choices=[('prod', 'Component (added to the product)'), ('cons', 'Consumable'), ('ener', 'Electricity or heat'), ('util', 'Utility or equipment'), ('trans', 'Transport'), ('pack', 'Packaging'), ('react', 'Reactant'), ('waste', 'Waste')], max_length=5),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='taric_code',
            field=models.CharField(blank=True, help_text='(customs code)', max_length=20, verbose_name='TARIC code'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x71c689400220>', max_length=50),
        ),
    ]
