# Generated by Django 5.2.8 on 2026-01-12 10:29

import django.db.models.deletion
import django_countries.fields
import dpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0020_alter_dppdetails_options_alter_productbatch_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DppDetails',
        ),
        migrations.RemoveField(
            model_name='process',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='production_line',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='upload_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='envexchange',
            old_name='observed',
            new_name='is_observed',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='biobased_percentage',
            new_name='biobased_fraction',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='recyclable_percentage',
            new_name='recyclable_fraction',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='recycled_content',
            new_name='recycled_fraction',
        ),
        migrations.RenameField(
            model_name='productexchange',
            old_name='observed',
            new_name='is_observed',
        ),
        migrations.RemoveField(
            model_name='backgroundprocess',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='backgroundprocess',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='backgroundprocess',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='backgroundprocess',
            name='functional_flow',
        ),
        migrations.RemoveField(
            model_name='backgroundprocess',
            name='location',
        ),
        migrations.RemoveField(
            model_name='backgroundprocess',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='process',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='process',
            name='location',
        ),
        migrations.RemoveField(
            model_name='process',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='CPV_code',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='GS1_GPC_code',
        ),
        migrations.AddField(
            model_name='activity',
            name='amount',
            field=models.FloatField(default=1, help_text='Reference number of units produced'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='activity',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(dpp.models.get_unknown_company), to='dpp.company', verbose_name='Producing company'),
        ),
        migrations.AddField(
            model_name='document',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Author, issuer or publisher', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpp.organization'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundprocess',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='circularityevaluation',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report describing the circularity assessment, and manual for monitoring and updating the circularity metrics.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circularity_eval', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='process',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='type',
            field=models.CharField(choices=[('prod', 'Component (added to the product)'), ('cons', 'Consumable'), ('ener', 'Electricity or heat'), ('util', 'Utility or equipment'), ('serv', 'Service'), ('pack', 'Packaging'), ('react', 'Reactant'), ('waste', 'Waste')], max_length=5),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='operator',
            field=models.ForeignKey(default=0, on_delete=models.SET(dpp.models.get_unknown_company), to='dpp.company', verbose_name='Producing company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x77206ae10680>', max_length=50),
        ),
        migrations.CreateModel(
            name='ManufacturingProcess',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.activity')),
                ('modified_at', models.DateField(auto_now=True)),
                ('functional_flow', models.OneToOneField(help_text='The output product of this manufacturing process.', on_delete=django.db.models.deletion.RESTRICT, related_name='produced_by_other', to='dpp.productmodel', verbose_name='Main product')),
            ],
            bases=('dpp.activity',),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='manufacturingprocess_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.manufacturingprocess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bop', to='dpp.productionline'),
        ),
        migrations.AddField(
            model_name='transport',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='dpp.productionline'),
        ),
    ]
