# Generated by Django 5.2.8 on 2026-01-12 12:28

import datetime
import django.core.validators
import django.db.models.deletion
import dpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0021_rename_upload_date_document_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='process',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bop', to='dpp.productionline'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7a54d16c0040>', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='dpp.productionline'),
        ),
        migrations.CreateModel(
            name='DppDetails',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dpp.productmodel')),
                ('CPV_code', models.CharField(blank=True, help_text='Common Procurement Vocabulary code', max_length=20)),
                ('GS1_GPC_code', models.CharField(blank=True, help_text='Global Product Classification code', max_length=20)),
                ('warranty_period', models.DecimalField(decimal_places=1, default=0, help_text='Warranty period in years', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('spare_parts_availability_duration', models.DecimalField(decimal_places=1, default=0, help_text='Spare parts availability in years', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('takeback_system', models.CharField(choices=[('no', 'No take-back system'), ('basic', 'Collection on request'), ('active', 'Structured take-back with dedicated channels or collection points'), ('advanced', 'Certified, traceable take-back system')], default='no', max_length=10)),
                ('origin', models.ForeignKey(on_delete=models.SET(dpp.models.get_unknown_company), related_name='manufactured_products', to='dpp.company')),
                ('quality_compliance_documents', models.ManyToManyField(blank=True, to='dpp.document')),
                ('vendor_or_importer', models.ForeignKey(blank=True, null=True, on_delete=models.SET(dpp.models.get_unknown_importer), related_name='sold_products', to='dpp.importer', verbose_name='Responsible Economic Operator')),
            ],
            options={
                'verbose_name': 'DPP details',
                'verbose_name_plural': 'DPP details',
            },
        ),
    ]
