# Generated by Django 5.2.8 on 2026-01-13 14:41

import django.db.models.deletion
import dpp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0022_alter_document_issue_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sales', 'Sales or ownership transfer'), ('test', 'Inspection'), ('Maintenance', [('corrective', 'Repair'), ('software', 'Software update'), ('performance', 'Performance upgrade'), ('safety', 'Safety improvement'), ('energy_optimization', 'Energy optimization'), ('compliance', 'Compliance update'), ('other', 'Other maintenance')]), ('disassembly', 'Disassembly'), ('Closing the loop', [('R3', 'Reuse'), ('R5', 'Refurbish'), ('R6', 'Remanufacture'), ('R7', 'Repurpose')]), ('End-of-life treatment', [('recycling', 'Recycling'), ('landfill', 'Landfilling'), ('incineration', 'Incineration'), ('stockpiling', 'Stockpiling'), ('disposal', 'Disposal (unspecified)')])], max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('activity_data', models.ForeignKey(default=dpp.models.LifeCycleEvent.get_empty_activity, help_text='Activity describing the inputs and outputs (optional).', on_delete=django.db.models.deletion.SET_DEFAULT, to='dpp.manufacturingprocess')),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpp.document')),
                ('operator', models.ForeignKey(help_text='Entity that performs this event.', on_delete=django.db.models.deletion.CASCADE, to='dpp.serviceoperator')),
            ],
        ),
        migrations.RemoveField(
            model_name='replacedcomponent',
            name='new_component',
        ),
        migrations.RemoveField(
            model_name='replacedcomponent',
            name='old_component',
        ),
        migrations.RemoveField(
            model_name='replacedcomponent',
            name='service_record',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='maintenance_plan',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_event',
        ),
        migrations.AddField(
            model_name='productitem',
            name='circularity',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7227537aa7a0>', max_length=50),
        ),
        migrations.CreateModel(
            name='DisassemblyEvent',
            fields=[
                ('lifecycleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.lifecycleevent')),
            ],
            bases=('dpp.lifecycleevent',),
        ),
        migrations.CreateModel(
            name='InspectionEvent',
            fields=[
                ('lifecycleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.lifecycleevent')),
                ('diagnostic_results', models.ManyToManyField(blank=True, to='dpp.document')),
            ],
            bases=('dpp.lifecycleevent',),
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('lifecycleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.lifecycleevent')),
                ('description', models.TextField(max_length=300)),
                ('affected_functionality', models.CharField(blank=True, max_length=200)),
                ('software_or_hardware', models.BooleanField(choices=[(True, 'Software'), (False, 'Hardware')])),
                ('root_cause', models.TextField(blank=True, max_length=300)),
                ('diagnostics_performed', models.TextField(blank=True, max_length=300)),
                ('corrective_action', models.TextField(blank=True, max_length=300)),
            ],
            bases=('dpp.lifecycleevent',),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_events', to='dpp.productitem'),
        ),
        migrations.CreateModel(
            name='ItemExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(help_text='Inputs are positive, outputs are negative.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.lifecycleevent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.productitem')),
            ],
        ),
        migrations.DeleteModel(
            name='EndOfLife',
        ),
        migrations.DeleteModel(
            name='ReplacedComponent',
        ),
        migrations.DeleteModel(
            name='ServiceEvent',
        ),
        migrations.DeleteModel(
            name='ServiceRecord',
        ),
    ]
