# Generated by Django 5.2.8 on 2026-01-14 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0023_lifecycleevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecycleevent',
            name='maintenance_plan',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='maintenance_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='dpp.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='registration_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7d56a90a68e0>', max_length=50),
        ),
        migrations.DeleteModel(
            name='CircularityEnabler',
        ),
    ]
