# Generated by Django 5.2.8 on 2026-01-16 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0024_remove_lifecycleevent_maintenance_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingprocess',
            name='facility_id',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Unique facility identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionline',
            name='facility_id',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Unique facility identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7ee712a33060>', max_length=50),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_of', to='dpp.productmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composed_of', to='dpp.productmodel')),
            ],
            options={
                'verbose_name': 'Replaceable component',
                'ordering': ['product', 'component'],
                'unique_together': {('product', 'component')},
            },
        ),
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concentration_in', to='dpp.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentration', to='dpp.productmodel')),
            ],
            options={
                'ordering': ['product', 'material'],
                'unique_together': {('product', 'material')},
            },
        ),
    ]
