# Generated by Django 5.2.8 on 2026-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0025_manufacturingprocess_facility_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturingprocess',
            old_name='facility_id',
            new_name='facility',
        ),
        migrations.RenameField(
            model_name='productionline',
            old_name='facility_id',
            new_name='facility',
        ),
        migrations.AddField(
            model_name='activity',
            name='facility_id',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Unique facility identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default='<function SustainabilityEvaluation.get_year at 0x7ee5d4b66d40>', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='envexchange',
            unique_together={('process', 'substance', 'compartment', 'direction')},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='facility_id',
        ),
    ]
