# Generated by Django 5.2.8 on 2026-01-26 09:21

import django.db.models.deletion
import dpp.models
from django.db import migrations, models


def copy_id_to_flow_ptr(apps, schema_editor):
    """Function to migrate ProductModel.id to new Flow model"""
    # Get the ProductModel and Flow model classes
    ProductModel = apps.get_model('dpp', 'ProductModel')
    Flow = apps.get_model('dpp', 'Flow')
    
    for product in ProductModel.objects.all():
        # Create a Flow instance as parent
        flow_instance = Flow.objects.create(id=product.id)
        # Link the new flow to the product
        product.flow_ptr = flow_instance
        product.save(update_fields=["flow_ptr"])

class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0026_remove_facility_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='flow_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, null=True, to='dpp.flow'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_id_to_flow_ptr),
        migrations.AlterField(
            model_name='productmodel',
            name='flow_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.flow'),
            preserve_default=False,
        ),
        migrations.DeleteModel(name='productbatch'),
        migrations.DeleteModel(name='secondaryproduct'),
        migrations.RemoveField(model_name='productitem', name='product_batch'),
        migrations.AlterField(
            model_name='envexchange',
            name='compartment',
            field=models.CharField(choices=[('Air', [('air-urban', 'Urban air'), ('air-rural', 'Non-urban air or from high stacks'), ('air-lt', 'Long-term'), ('air-indoor', 'Indoor'), ('air-strato', '10-30 km above ground'), ('air', 'Unspecified')]), ('uptake', 'Direct human uptake'), ('Soil', [('soil-agri', 'Agricultural'), ('soil-forest', 'Forest'), ('soil-indu', 'Industrial'), ('soil', 'Unspecified')]), ('Water', [('surface_water', 'Surface water'), ('seawater', 'Seawater'), ('groundwater', 'Groundwater'), ('groundwater-lt', 'Groundwater, long term'), ('groundwater-deep', 'Deep underground wells'), ('water', 'Unspecified')])], max_length=20),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='temporal_scope',
            field=models.CharField(default=dpp.models.SustainabilityEvaluation.get_year, max_length=50),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='circularityevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_of', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='component',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composed_of', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='concentration',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentration', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='functional_flow',
            field=models.OneToOneField(help_text='The output product of this manufacturing process.', on_delete=django.db.models.deletion.RESTRICT, related_name='produced_by_other', to='dpp.flow', verbose_name='Main product'),
        ),
        migrations.AlterField(
            model_name='process',
            name='functional_flow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='dpp.flow', verbose_name='Main output'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_by', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='final_product',
            field=models.OneToOneField(help_text='The output product of this production line', on_delete=django.db.models.deletion.RESTRICT, to='dpp.flow', verbose_name='Final product'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='dppdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dpp.flow'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.CreateModel(
            name='SecondaryProduct',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.productmodel')),
                ('circularity', models.CharField(choices=[('R3', 'reused'), ('R5', 'refurbished'), ('R6', 'remanufactured'), ('R7', 'repurposed'), ('R8', 'recycled'), ('in', 'incinerated'), ('lf', 'landfilled'), ('-', 'unknown')], default='-', max_length=2)),
                ('is_waste', models.BooleanField(default=False)),
            ],
            bases=('dpp.productmodel',),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('flow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpp.flow')),
                ('batch_number', models.PositiveIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batch', to='dpp.flow')),
            ],
            options={
                'verbose_name_plural': 'Product batches',
            },
            bases=('dpp.flow',),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dpp.productbatch'),
            preserve_default=False,
        ),
    ]
