# Generated by Django 5.2.8 on 2026-01-27 14:45

import django.db.models.deletion
import django_countries.fields
import uuid
import dpp.models
from django.db import migrations, models


def activity_operator_to_facility(apps, schema_editor):
    """Function to migrate operator to facility"""
    Activity = apps.get_model('dpp', 'Activity')
    Facility = apps.get_model('dpp', 'Facility')
    
    for activity in Activity.objects.all():
        operator = activity.operator
        if not operator:
            print(f"{activity} has no operator.")
            return
        # Create a Facility instance
        facility = Facility.objects.create(
            operator=operator, country=operator.country, address=operator.address
        )
        activity.facility_id = facility.pk
        activity.save()

def production_operator_to_facility(apps, schema_editor):
    """Function to migrate operator to facility"""
    ProductionLine = apps.get_model('dpp', 'ProductionLine')
    Facility = apps.get_model('dpp', 'Facility')
    
    for activity in ProductionLine.objects.all():
        operator = activity.operator
        # Create a Facility instance
        facility = Facility.objects.create(
            operator=operator, country=operator.country, address=operator.address
        )
        activity.facility_id = facility.pk
        activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0027_introduce_flow'),
    ]

    operations = [
        # Remove, because the date is already specified in CircularityEvaluation
        migrations.RemoveField(
            model_name='circularityscore',
            name='modified_at',
        ),
        # Rename 'vendor_or_importer' to 'importer'
        migrations.RemoveField(
            model_name='dppdetails',
            name='vendor_or_importer',
        ),
        migrations.AddField(
            model_name='dppdetails',
            name='importer',
            field=models.ForeignKey(blank=True, help_text='Specify if the product is imported from outside the EU.', null=True, on_delete=models.SET(dpp.models.get_unknown_importer), related_name='imported_products', to='dpp.importer'),
        ),
        # Issuer should actually be linked to a verified ID, but we keep it here for now
        migrations.AddField(
            model_name='metadata',
            name='issuer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dpp.institution'),
            preserve_default=False,
        ),
        # Generalized relation: any Activity can exchange (was Process)
        migrations.AlterField(
            model_name='envexchange',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_exchanges', to='dpp.activity'),
        ),
        # Add REO as field to DPP details (linked to item)
        migrations.AddField(
            model_name='metadata',
            name='reo',
            field=models.ForeignKey(default=1, help_text='The entity bearing legal responsibility for the DPP and the product.', on_delete=django.db.models.deletion.PROTECT, to='dpp.company', verbose_name='Responsible economic operator'),
            preserve_default=False,
        ),
        # Create Facility class, refer to it for location/operator
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique facility identifier', primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dpp.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='manufacturingprocess',
            name='facility',
        ),
        migrations.AddField(
            model_name='activity',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Production location', null=True, on_delete=django.db.models.deletion.CASCADE, to='dpp.facility'),
        ),
        migrations.RunPython(activity_operator_to_facility),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='facility',
        ),
        migrations.AddField(
            model_name='productionline',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Production location', null=True, on_delete=django.db.models.deletion.CASCADE, to='dpp.facility'),
        ),
        migrations.RunPython(production_operator_to_facility),
        migrations.RemoveField(
            model_name='productionline',
            name='operator',
        ),
    ]
