# Generated by Django 5.2.8 on 2026-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0028_introduce_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
