# Generated by Django 5.2.8 on 2026-02-03 11:16

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0029_alter_facility_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['operator', 'country', 'address'], 'verbose_name_plural': 'Facilities'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='material',
            name='reused_fraction',
        ),
        migrations.AddField(
            model_name='material',
            name='chemical_formula',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(default='JP', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, help_text='Location of the headquarters, or correspondence address', max_length=100),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='DPP_metadata',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dpp.metadata'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('country', 'address', 'operator')},
        ),
    ]
