# Generated by Django 5.2.8 on 2026-02-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0030_alter_facility_options_remove_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productexchange',
            name='type',
            field=models.CharField(choices=[('prod', 'Component (part of the product)'), ('cons', 'Consumable'), ('ener', 'Electricity or heat'), ('util', 'Utility or equipment'), ('serv', 'Service'), ('pack', 'Packaging'), ('react', 'Reactant'), ('waste', 'Waste')], max_length=5),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0, help_text='Highest successfully completed step (1-5)')),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('production_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dpp.productionline')),
            ],
        ),
    ]
