# Generated by Django 5.2.8 on 2026-02-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0032_repair_backgroundprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedProcess',
        ),
        migrations.RemoveField(
            model_name='dppdetails',
            name='origin',
        ),
        migrations.AlterField(
            model_name='dppdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='itemexchange',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_exchanges', to='dpp.lifecycleevent'),
        ),
        migrations.AlterField(
            model_name='sustainabilityevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_evaluation', to='dpp.flow'),
        ),
    ]
