# Generated by Django 5.2.8 on 2026-02-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0033_delete_sharedprocess_add_related_names_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circularityevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circularity_evaluation', to='dpp.flow'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Technical document', [('technical_drawing', 'Technical drawing'), ('safety_sheet', 'Safety sheet'), ('conformity_certificate', 'Conformity certificate'), ('mass_balance', 'Mass balance'), ('energy_balance', 'Energy balance'), ('other', 'Other')]), ('Compliance document', [('compliance', 'Compliance report'), ('quality_cert', 'Quality certificate'), ('safety_data', 'Safety data sheet'), ('legal', 'Legal document'), ('labor', 'Labor compliance'), ('qms', 'Quality Management System certificate'), ('warranty', 'Warranty information'), ('spare_parts', 'Spare parts availability'), ('takeback', 'Return and take-back')]), ('Manuals', [('manual', 'User manual'), ('maintenance', 'Maintenance manual'), ('installation', 'Installation guide'), ('eol', 'End-of-life guidelines'), ('datasheet', 'Product data sheet')]), ('Labels', [('label', 'Voluntary label'), ('energy_label', 'Energy label'), ('ecolabel', 'Ecolabel'), ('recycling_label', 'Recycling label'), ('legal', 'Legal markings')])], default='other', max_length=25, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='DPP_metadata',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_item', to='dpp.metadata'),
        ),
    ]
