# Generated by Django 5.2.8 on 2026-02-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0034_alter_circularityevaluation_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dppdetails',
            old_name='quality_compliance_documents',
            new_name='compliance_documents',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='DPP_metadata',
        ),
        migrations.AddField(
            model_name='metadata',
            name='product_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dpp_metadata', to='dpp.productitem'),
            preserve_default=False,
        ),
    ]
