# Generated by Django 5.2.8 on 2026-03-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0035_rename_quality_compliance_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='GTIN_code',
        ),
        migrations.AddField(
            model_name='productbatch',
            name='GTIN_code',
            field=models.CharField(default='8712345678901', help_text='Global Trade Item Number (or EAN)', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='access_link_base',
            field=models.URLField(blank=True, help_text='Base URL to DPP record.'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='access_log_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='access_policy',
            field=models.URLField(blank=True, help_text='URL to data access terms and conditions.'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='amount',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many items need a DPP.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='audit_trail_mechanism',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Log files'), (2, 'Immutable ledger')], default=0),
        ),
        migrations.AddField(
            model_name='publisher',
            name='credential_format',
            field=models.CharField(choices=[('json_ld', 'JSON-LD'), ('verifialble', 'Verifiable credential'), ('xml', 'XML'), ('other', 'Other')], default='xml', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='issuer',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='dpp.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='language',
            field=models.CharField(default='EN', help_text='Language used in descriptions', max_length=20),
        ),
        migrations.AddField(
            model_name='publisher',
            name='registration_numbers',
            field=models.CharField(blank=True, help_text='Range of numbers (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='publisher',
            name='reo',
            field=models.ForeignKey(default=4, help_text='The entity bearing legal responsibility for the DPP and the product.', on_delete=django.db.models.deletion.PROTECT, to='dpp.company', verbose_name='Responsible economic operator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='storage_location',
            field=models.SmallIntegerField(choices=[(0, 'Undeclared'), (1, 'On-premise server'), (2, 'Commercial cloud server'), (3, 'Centralized certified server'), (4, 'Decentralized storage')], default=0),
        ),
        migrations.AddField(
            model_name='publisher',
            name='update_interval',
            field=models.CharField(choices=[('-', 'never'), ('W', 'weekly'), ('M', 'monthly'), ('Q', 'quarterly'), ('A', 'annually'), ('E', 'event_driven')], default='-', max_length=2),
        ),
        migrations.AddField(
            model_name='publisher',
            name='verification_type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Digital signature'), (2, 'Third party'), (3, 'Blockchain')], default=0),
        ),
        migrations.AddField(
            model_name='publisher',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='version',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sustainabilityscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_score', to='dpp.sustainabilityevaluation'),
        ),
    ]
