# Generated by Django 5.2.8 on 2026-03-13 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0036_move_gtin_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='productbatch',
            old_name='GTIN_code',
            new_name='GTIN',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='envexchange',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturingprocess',
            name='energy_balance',
            field=models.ForeignKey(blank=True, help_text='A document showing all energy flows exchanges of the process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_balance', to='dpp.document'),
        ),
        migrations.AddField(
            model_name='manufacturingprocess',
            name='mass_balance',
            field=models.ForeignKey(blank=True, help_text='A document showing all material exchanges of the process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_balance', to='dpp.document'),
        ),
        migrations.AddField(
            model_name='productexchange',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transport',
            name='utilisation_ratio',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Technical document', [('technical_drawing', 'Technical drawing'), ('safety_sheet', 'Safety sheet'), ('conformity_certificate', 'Conformity certificate'), ('mass_balance', 'Mass balance'), ('energy_balance', 'Energy balance'), ('other', 'Other')]), ('Compliance document', [('compliance', 'Compliance report'), ('quality_cert', 'Quality certificate'), ('safety_data', 'Safety data sheet'), ('legal', 'Legal document'), ('labor', 'Labor compliance'), ('qms', 'Quality Management System certificate'), ('warranty', 'Warranty information'), ('spare_parts', 'Spare parts availability'), ('takeback', 'Return and take-back')]), ('Manuals', [('manual', 'User manual'), ('maintenance', 'Maintenance manual'), ('installation', 'Installation guide'), ('eol', 'End-of-life guidelines'), ('datasheet', 'Product data sheet')]), ('Labels', [('label', 'Voluntary label'), ('energy_label', 'Energy label'), ('ecolabel', 'Ecolabel'), ('circularity_label', 'Circularity label'), ('legal', 'Legal markings')])], default='other', max_length=25, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='dppdetails',
            name='CPV_code',
            field=models.CharField(blank=True, help_text='Common Procurement Vocabulary code', max_length=8),
        ),
        migrations.AlterField(
            model_name='dppdetails',
            name='GS1_GPC_code',
            field=models.CharField(blank=True, help_text='Global Product Classification code', max_length=9),
        ),
        migrations.AlterField(
            model_name='emission',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='hazardousmaterial',
            name='CAS_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='importer',
            name='EORI_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='energy_balance',
            field=models.ForeignKey(blank=True, help_text='Add a document showing all energy flows going in and out of the production line. (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_energy_balance', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='mass_balance',
            field=models.ForeignKey(blank=True, help_text='Add a document showing all material flows going in and out of the production line. (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_mass_balance', to='dpp.document'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='error_message',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
