# Generated by Django 5.2.8 on 2026-03-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0037_rename_uid_facility_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sustainabilityscore',
            old_name='impact_category',
            new_name='impact_indicator',
        ),
        migrations.RemoveField(
            model_name='envexchange',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='maintenanceevent',
            name='corrective_action',
        ),
        migrations.RemoveField(
            model_name='maintenanceevent',
            name='diagnostics_performed',
        ),
        migrations.RemoveField(
            model_name='productexchange',
            name='shape',
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='description',
            field=models.TextField(blank=True, help_text='Diagnostic tools or methods used', max_length=300),
        ),
        migrations.AddField(
            model_name='sustainabilityevaluation',
            name='is_environmental',
            field=models.BooleanField(default=True, verbose_name='Whether this is an environmental sustainability evaluation (LCA).'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('other', 'Other'), ('Technical document', [('technical_drawing', 'Technical drawing'), ('safety_sheet', 'Safety sheet'), ('conformity_certificate', 'Conformity certificate'), ('mass_balance', 'Mass balance'), ('energy_balance', 'Energy balance'), ('datasheet', 'Product data sheet')]), ('Compliance document', [('compliance', 'Compliance report'), ('quality_cert', 'Quality certificate'), ('safety_data', 'Safety data sheet'), ('legal', 'Legal document'), ('labor', 'Labor compliance'), ('qms', 'Quality Management System certificate'), ('warranty', 'Warranty information'), ('spare_parts', 'Spare parts availability'), ('takeback', 'Return and take-back')]), ('Manual', [('manual', 'User manual'), ('maintenance', 'Maintenance manual'), ('installation', 'Installation guide'), ('eol', 'End-of-life guidelines')]), ('Label', [('label', 'Voluntary label'), ('energy_label', 'Energy label'), ('ecolabel', 'Ecolabel'), ('circularity_label', 'Circularity label'), ('legal', 'Legal markings')])], default='other', max_length=25, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='dppdetails',
            name='takeback_system',
            field=models.CharField(choices=[('no', 'No take-back system'), ('basic', 'Collection on request'), ('active', 'Structured take-back with dedicated channels or collection points'), ('advanced', 'Certified, traceable take-back system')], default='no', max_length=10, verbose_name='Take-back system'),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='loc',
            field=models.FloatField(blank=True, help_text='for (log)normal and triangular distribution', null=True, verbose_name='Mean or mode'),
        ),
        migrations.AlterField(
            model_name='envexchange',
            name='scale',
            field=models.FloatField(blank=True, help_text='or log-space standard deviation', null=True, verbose_name='Standard deviation'),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='root_cause',
            field=models.TextField(blank=True, help_text='For repair only. Specify the root cause of failure.', max_length=300),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='functional_flow',
            field=models.OneToOneField(help_text='The output product of this manufacturing process.', on_delete=django.db.models.deletion.RESTRICT, related_name='manufacturing_information', to='dpp.flow', verbose_name='Main product'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dpp.organization'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='reo',
            field=models.ForeignKey(help_text='The entity bearing legal responsibility for the DPP and the product.', on_delete=django.db.models.deletion.PROTECT, related_name='reo_of', to='dpp.company', verbose_name='Responsible economic operator'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='loc',
            field=models.FloatField(blank=True, help_text='for (log)normal and triangular distribution', null=True, verbose_name='Mean or mode'),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='scale',
            field=models.FloatField(blank=True, help_text='or log-space standard deviation', null=True, verbose_name='Standard deviation'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='error_message',
            field=models.TextField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dpp.organization'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='production_line',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dpp.productionline'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='reo',
            field=models.ForeignKey(help_text='The entity bearing legal responsibility for the DPP and the product.', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_for', to='dpp.company', verbose_name='Responsible economic operator'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Highest successfully completed step (1-5)'),
        ),
    ]
