# Generated by Django 5.2.8 on 2026-04-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0038_rename_impact_category_sustainabilityscore_impact_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='functional_flow',
            field=models.OneToOneField(help_text='The output product of this manufacturing process.', on_delete=django.db.models.deletion.RESTRICT, related_name='manufacturing_info', to='dpp.flow', verbose_name='Main product'),
        ),
    ]
