# Generated by Django 6.0.5 on 2026-06-17 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0039_alter_instruction_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batch', to='dpp.productmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='transport',
            unique_together={('production_line', 'product')},
        ),
    ]
