# Generated by Django 6.1.1 on 2026-09-29 11:59

from django.db import migrations, models

def fix_m2m_labels_to_ids(apps, schema_editor):
    Instruction = apps.get_model('dpp', 'Instruction')
    Document = apps.get_model('dpp', 'Document')
    
    # Get the M2M through table
    Through = Document.instructions.through

    # In the M2M table, replace instruction label with id (int).
    for row in Through.objects.all():
        try:
            instruction = Instruction.objects.get(label=row.instruction_id)
            row.instruction_id = instruction.id
            row.save()
        except Instruction.DoesNotExist:
            row.delete()  # orphaned row, label no longer exists
    schema_editor.execute("PRAGMA foreign_keys = ON;")


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0041_alter_transport_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('other', 'Other'), ('Technical document', [('technical_drawing', 'Technical drawing'), ('safety_sheet', 'Safety sheet'), ('conformity_certificate', 'Conformity certificate'), ('mass_balance', 'Mass balance'), ('energy_balance', 'Energy balance'), ('datasheet', 'Product data sheet')]), ('Compliance document', [('compliance', 'Compliance report'), ('quality_cert', 'Quality certificate'), ('safety_data', 'Safety data sheet'), ('legal', 'Legal document'), ('labor', 'Labor compliance'), ('qms', 'Quality Management System certificate'), ('warranty', 'Warranty information'), ('spare_parts', 'Spare parts availability'), ('takeback', 'Return and take-back')]), ('manual', 'Manual'), ('Label', [('label', 'Voluntary label'), ('energy_label', 'Energy label'), ('ecolabel', 'Ecolabel'), ('circularity_label', 'Circularity label'), ('legal', 'Legal markings')])], default='other', max_length=25, verbose_name='Document type'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='instructions',
        ),
        migrations.AddField(
            model_name='document',
            name='instructions',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply. Instructions included in this document (only for manuals)', to='dpp.instruction'),
        ),
        migrations.DeleteModel(name='instruction'),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RunPython(
            fix_m2m_labels_to_ids, migrations.RunPython.noop
        ),
    ]
