# Generated by Django 6.1.1 on 2026-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0042_fix_instructions_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='gtin',
            field=models.CharField(
                default='111111',
                help_text='Global Trade Item Number (or EAN)',
                max_length=13,
                verbose_name='GTIN'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='GTIN',
            field=models.CharField(
                help_text='Global Trade Item Number (or EAN)', max_length=13
            ),
        ),
    ]
