# Generated by Django 6.0.5 on 2026-07-08 12:48

import django.core.validators
import django.db.models.deletion
import dss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=10, null=True, validators=[dss.models.validate_number_or_range])),
            ],
        ),
        migrations.CreateModel(
            name='McdaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.CharField(choices=[('deterministic', 'Deterministic'), ('uncertain', 'Uncertain')], max_length=15, null=True)),
                ('method', models.CharField(choices=[('promethee_like', 'Promethee Like'), ('promethee', 'Promethee')], max_length=15, null=True)),
                ('weight_mode', models.CharField(choices=[('flat', 'Flat'), ('group', 'Group'), ('hierarchical', 'Hierarchical')], max_length=12, null=True)),
                ('veto_type', models.CharField(choices=[('no', 'No'), ('hard', 'Hard'), ('soft', 'Soft')], max_length=4, null=True)),
                ('group_weights', models.JSONField(null=True)),
                ('local_weights', models.JSONField(null=True)),
                ('thresholds', models.JSONField(null=True)),
                ('veto_thresholds', models.JSONField(null=True)),
                ('penalty_factor', models.FloatField(default=0.5)),
                ('sampling_mode', models.CharField(choices=[('random', 'Random'), ('bounded', 'Bounded'), ('ordered', 'Ordered'), ('bounded_ordered', 'Bounded Ordered')], max_length=15, null=True)),
                ('n_samples', models.IntegerField(null=True)),
                ('alpha', models.FloatField(null=True)),
                ('alpha_group', models.FloatField(null=True)),
                ('alpha_local', models.FloatField(null=True)),
                ('group_order', models.JSONField(null=True)),
                ('local_order', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('direction', models.CharField(help_text="Enter 'min', 'max' or a target value", max_length=10, validators=[dss.models.validate_number_or_range])),
                ('weight', models.CharField(max_length=10, null=True, validators=[dss.models.validate_number_or_range])),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria', to='dss.group')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='dss.mcdasession')),
            ],
            options={
                'verbose_name_plural': 'Criteria',
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('group1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_higher', to='dss.group')),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_lower', to='dss.group')),
            ],
        ),
        migrations.CreateModel(
            name='LocalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('criterion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_higher', to='dss.criterion')),
                ('criterion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_lower', to='dss.criterion')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.group')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.CharField(max_length=40)),
                ('values', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='dss.mcdasession')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='dss.mcdasession'),
        ),
    ]
