# Generated by Django 6.0.5 on 2026-07-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CritGroup',
        ),
    ]