# Generated by Django 6.0.5 on 2026-07-08 14:34

import dss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0002_rename_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='direction',
            field=models.CharField(blank=True, help_text="Enter 'min', 'max' or a target value", max_length=10, validators=[dss.models.validate_number_or_range]),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=10, validators=[dss.models.validate_number_or_range]),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='decisionmatrix',
            old_name='alternative',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='criterion',
            name='direction',
            field=models.CharField(blank=True, help_text="Enter 'min', 'max' or a target value", max_length=10, validators=[dss.models.validate_direction]),
        ),
        migrations.AlterUniqueTogether(
            name='decisionmatrix',
            unique_together={('session', 'name')},
        ),
    ]
