# Generated by Django 6.0.5 on 2026-07-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_alter_criterion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='session',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='dss.mcdasession'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='localorder',
            name='group',
        ),
        migrations.AddField(
            model_name='localorder',
            name='session',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='local_orders', to='dss.mcdasession'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='localorder',
            unique_together={('session', 'criterion1', 'criterion2')},
        ),
        migrations.AlterUniqueTogether(
            name='grouporder',
            unique_together={('session', 'group1', 'group2')},
        ),
    ]
