# Generated by Django 6.0.5 on 2026-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0004_alter_localorder_grouporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mcdasession',
            name='user_type',
            field=models.CharField(choices=[('pd', 'Process developer'), ('kam', 'Key account manager')], max_length=3, null=True),
        ),
    ]
