# Generated by Django 6.0.5 on 2026-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0007_replace_results_data_with_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcdasession',
            name='group_order',
        ),
        migrations.RemoveField(
            model_name='mcdasession',
            name='local_order',
        ),
        migrations.RemoveField(
            model_name='mcdasession',
            name='sampling_mode',
        ),
        migrations.AddField(
            model_name='mcdasession',
            name='crit_ranks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mcdasession',
            name='criterion_weights',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mcdasession',
            name='group_ranks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mcdasession',
            name='local_ranks',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mcdasession',
            name='scenario',
            field=models.CharField(choices=[('deterministic', 'Deterministic'), ('random', 'Random'), ('bounded', 'Bounded'), ('ordered', 'Ordered'), ('bounded_ordered', 'Bounded Ordered')], max_length=15, null=True),
        ),
    ]
