# Generated by Django 6.0.5 on 2026-09-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0008_remove_mcdasession_group_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='localorder',
            name='criterion1',
        ),
        migrations.RemoveField(
            model_name='localorder',
            name='criterion2',
        ),
        migrations.RemoveField(
            model_name='localorder',
            name='session',
        ),
        migrations.DeleteModel(
            name='GroupOrder',
        ),
        migrations.DeleteModel(
            name='LocalOrder',
        ),
    ]
